// This file is generated by ./make.dart

class BuildData {
  static const String name = "2fa";
  static const int build = 5;
  static const String engine = "3.16.7";
  static const String buildAt = "2024-01-16 16:01:49";
  static const int modifications = 24;
}
