// This file is generated by ./make.dart

class BuildData {
  static const String name = "2fa";
  static const int build = 4;
  static const String engine = "3.16.2";
  static const String buildAt = "2023-12-05 13:53:01";
  static const int modifications = 1;
}
